{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "yes"
    app: {{ template "grafana.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.server.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "grafana.server.fullname" . }}-datasource-prometheus
data:
  prometheus-datasource.yml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://{{ printf "%s-%s" .Release.Name "server" }}:{{ .Values.prometheusPort }}
      access: proxy
{{- end }}
